apiVersion: v1
kind: ConfigMap
metadata:
  name: serviceshoster-config
data:
  appsettings.json: |
    {
      "Storage": {
        "Type": "InMemory"
      },
      "Auth": {
        "Authority": "http://keycloak-service:8080/realms/master",
        "Audience": "",
        "RequireHttpsMetadata": false
      }
    }